name: optics
version: 0.0.1
description: A simple console application.
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  source_gen: any
dev_dependencies:
  build_runner: any
  test: any
  benchmark_harness: '>=1.0.2'
